// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:07f3d507-0381-4fb8-b228-3bca77136a62",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_CtnlbDKhl",
    "aws_user_pools_web_client_id": "1qop2v0tes2mqngi0kcqo5ep83",
    "aws_appsync_graphqlEndpoint": "https://l77hjoeqjjcp3h7cio2r7h5jj4.appsync-api.ap-southeast-2.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
